# frontend/Dockerfile

# Use an official Node runtime as a parent image
FROM node:14

# Set working directory
WORKDIR /usr/src/app

# Install dependencies
COPY package*.json ./
RUN npm install

# Add the rest of the code
COPY . .

# Build the app
RUN npm run build

# Install serve package to serve the build directory
RUN npm install -g serve

# Expose port 3000
EXPOSE 3000

# Start the application
CMD ["serve", "-s", "build", "-l", "3000"]